apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ccs.ornl.gov/fs: olcf
  labels:
    app: darshan-utils
  name: darshan-utils
spec:
  selector:
    matchLabels:
      app: darshan-utils
  replicas: 1
  template:
    metadata:
      labels:
        app: darshan-utils
    spec:
      containers:
        - name: darshan-utils
          image: image-registry.openshift-image-registry.svc:5000/gen119blazingsql/darshanutils
          command: ['/bin/bash']
          env:
            - name: PROJWORK
              value: /gpfs/alpine/proj-shared
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 4Gi
          stdin: true
      restartPolicy: Always
status: {}
