apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ccs.ornl.gov/fs: olcf
  labels:
    app: darshan-utils
  name: darshan-utils
spec:
  selector:
    matchLabels:
      app: darshan-utils
  replicas: 1
  template:
    metadata:
      labels:
        app: darshan-utils
    spec:
      containers:
        - name: darshan-utils
          image: image-registry.openshift-image-registry.svc:5000/gen150-app/iipimage
          command: ['/bin/sh','-c']
          args: ['./run_iipsrv.sh'] 
          env:
            - name: CA_IIP_ROOT
              value: /gpfs/alpine/proj-shared/gen150/caMicroscope/apache2
          ports:
            - name: ca-iip-apache
              containerPort: 80
            - name: ca-iip-port
              containerPort: 8080
            - name: ca-iip-utils
              containerPort: 8443
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '4'
              memory: 8Gi
          stdin: true
      restartPolicy: Always
status: {}
